### ISSUE TITLE
Socket.io

### ISSUE THREAD

**Issue by ghost** [andrewhodel/http-fileserver#2]
Replacing node-static into existing code, breaks socket.io:

\
![socket io](https://cloud.githubusercontent.com/assets/7695323/11275422/3dcd76c2-8ee6-11e5-8966-2d57593ef1bd.PNG)
![socket io2](https://cloud.githubusercontent.com/assets/7695323/11275423/3dce1f0a-8ee6-11e5-9bb4-14f9bf135c11.PNG)

Suspect because of 
if (filename.substr(filename.length - 1) == '/') {
        filename += 'index.html';
    }

**Comment by andrewhodel** [comment]
Oh this is all on Windows.

Jeez man do you really honestly truly use that OS?

**Comment by ghost** [comment]
(: I test on the worst, then it works on the best 

Sadly my users do too

**Comment by andrewhodel** [comment]
Strange workflow.

**Comment by ghost** [comment]
Depends what I am working on...

**Comment by ghost** [comment]
I didnt touch this:

var app = require('http').createServer(handler)
  , io = require('socket.io').listen(app)
  , fs = require('fs');

But in the usual code has:

app.listen(config.webPort);

which conflicts with your http.createServer(function(req, res) {  }).listen(config.port);  
So I took out the  app.listen(config.webPort);

Could break socket.io?

**Comment by andrewhodel** [comment]
That's why you don't use Express.

You're just writing it wrong.

**Comment by ghost** [comment]
Its not express.  Its straight from your old code:
https://github.com/andrewhodel/grblweb/blob/master/server.js#L31

**Comment by andrewhodel** [comment]
Don't you see that they are the same thing?

Aren't you looking at the variable declarations?

**Comment by andrewhodel** [comment]
Re Windows, I don't even know why you'd work with the worst in the first place.

Why not just work with the best, especially from a developer standpoint?

The only reason I could see caring about Windows and OS X would be games or something.  But real work seems easier on an open os.

**Comment by ghost** [comment]
![screenshot from 2015-11-22 08-48-43](https://cloud.githubusercontent.com/assets/7695323/11322471/f0851962-90f5-11e5-8e9e-66b17229136a.png)

Well, now you can't blame Windows (;

So, can we fix it?

**Comment by andrewhodel** [comment]
Sure, isn't the error telling you what's wrong?

An Object doesn't have a method.  Then you just call that method directly and debug from there.

Link to the http instantiation line in the code.
